version: "3.9"

services:
  backend:
    build: ./project-backend
    container_name: flask-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./project-frontend
    container_name: static-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
